liip_imagine:
    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail :
                    size: [100, 100]
                    mode: outbound
        medium:
            quality: 75
            filters:
                thumbnail :
                    size: [320, 210]
                    mode: outbound                    `