vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /images/proprieties
            upload_destination: '%kernel.project_dir%/public/images/proprieties'
            namer: Vich\UploaderBundle\Naming\UniqidNamer